# Generated by Django 4.2.11 on 2024-06-12 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('logradouro', models.CharField(max_length=60, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=60, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=30, verbose_name='UF')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dados Usuário',
                'verbose_name_plural': 'Dados Usuários',
                'db_table': 'app_dados_usuario',
            },
        ),
    ]
